# Generated by Django 3.1.4 on 2021-01-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_maker', '0007_auto_20210105_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('status', models.CharField(default='xxx', max_length=3)),
                ('short_desc', models.TextField(default='This site was not scaned yet', max_length=1023, verbose_name='Some Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemaps', to='ads_maker.wsite'),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
