# Generated by Django 3.1.4 on 2021-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_maker', '0008_auto_20210106_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
