# Generated by Django 3.1.4 on 2021-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_maker', '0009_sitemap_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemap',
            old_name='count',
            new_name='count_sitemaps',
        ),
        migrations.AddField(
            model_name='sitemap',
            name='count_urls',
            field=models.IntegerField(default=0),
        ),
    ]
