# Generated by Django 3.1.4 on 2021-02-07 09:32

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255, verbose_name='Projects title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Projects title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Projects title')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='Projects title')),
                ('short_desc', models.TextField()),
                ('short_desc_ru', models.TextField(null=True)),
                ('short_desc_en', models.TextField(null=True)),
                ('short_desc_de', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('role', models.CharField(blank=True, max_length=125, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Учеба')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Учеба')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Учеба')),
                ('name_de', models.CharField(max_length=150, null=True, verbose_name='Учеба')),
            ],
            options={
                'verbose_name': 'Учеба',
                'verbose_name_plural': 'Учебы',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', sorl.thumbnail.fields.ImageField(upload_to='project_images/', verbose_name='Image file link')),
                ('cover', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cv.project', verbose_name='Link to project by ID')),
            ],
        ),
    ]
