# Generated by Django 3.1.4 on 2021-04-18 03:14

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20210211_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Работа')),
                ('position', models.TextField()),
                ('description', tinymce.models.HTMLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.AddField(
            model_name='study',
            name='degree',
            field=models.TextField(default='--none--'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='description',
            field=tinymce.models.HTMLField(default='--none--'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
