# Generated by Django 3.1.4 on 2021-02-05 10:40

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_project_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='file',
            field=sorl.thumbnail.fields.ImageField(upload_to='project_images/', verbose_name='Image file link'),
        ),
    ]
