# Generated by Django 3.1.4 on 2021-01-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_desc_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Projects title'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Projects title'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Projects title'),
        ),
    ]
