# Generated by Django 3.1.4 on 2021-04-18 03:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20210418_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_de',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='name_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='job',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='job',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='job',
            name='position_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='position_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='position_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='degree_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='degree_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='degree_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='description_de',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
