# Generated by Django 3.1.4 on 2021-02-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20210205_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
