# Generated by Django 3.1.4 on 2021-04-18 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20210418_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Скилл')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Уровень')),
                ('description', models.CharField(max_length=127, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=50, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=50, null=True, verbose_name='Должность')),
                ('position_de', models.CharField(max_length=50, null=True, verbose_name='Должность')),
                ('education', models.ManyToManyField(to='cv.Study', verbose_name='Образование')),
                ('jobs', models.ManyToManyField(to='cv.Job', verbose_name='Опыт работы')),
                ('projects', models.ManyToManyField(to='cv.Project', verbose_name='Мои проекты')),
                ('skills', models.ManyToManyField(to='cv.Skill', verbose_name='Скиллы')),
            ],
        ),
    ]
