# Generated by Django 3.1.4 on 2021-04-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_cv_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='slug',
            field=models.SlugField(default='--', max_length=25, unique=True, verbose_name='URL слаг'),
            preserve_default=False,
        ),
    ]
