# Generated by Django 3.1.4 on 2021-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_cv_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-end_date',), 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AddField(
            model_name='cv',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
