# Generated by Django 3.1.4 on 2021-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20210419_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='text_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
