# Generated by Django 3.1.4 on 2021-07-08 20:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_auto_20210707_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('company', models.CharField(max_length=255, verbose_name='To company')),
                ('date', models.DateField()),
                ('position', models.CharField(blank=True, max_length=125, null=True)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
