# Generated by Django 3.1.4 on 2021-07-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='to',
            field=models.CharField(default='Hiring Manager', max_length=255, verbose_name='To person'),
        ),
    ]
